pub mod anthropic;
pub mod auth;
pub mod browser;
pub mod claude;
pub mod config;
pub mod config_keys;
pub mod daemon;
pub mod logging;
pub mod monitor;
pub mod openai_compat;
pub mod paths;
pub mod project;
pub mod prompt;
pub mod provider;
pub mod providers;
pub mod registry;
pub mod request_identity;
pub mod retry;
pub mod server;
pub mod session;
pub mod setup;
pub mod shell;
pub mod traffic;
pub mod tui;
pub mod ui;
pub mod update;
pub mod usage;

pub use crate::anthropic::error::{ErrorDetail, ErrorEnvelope, json_error};
pub use crate::anthropic::schema::MessagesRequest;
pub use crate::provider::{AuthCommand, CliHandlers, Provider, RequestContext};
pub use crate::registry::Registry;
